import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
export const metadata: Metadata = {
  title: "Isaia - Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-950">
        <header className="w-full h-[50px] sticky top-0 z-50 mb-12 flex justify-center items-center ">
          <div className="w-full h-[100%] bg-slate-900 max-w-[400px] mx-auto md:max-w-[80%] rounded-full px-6">
            <ul className=" w-full h-full flex justify-between items-center gap-9">
              <div className="w-6 h-6">
                <Link href="/">
                  <Image
                    src="/icon/icon.png"
                    alt="Icon"
                    width={500}
                    height={300}
                  />
                </Link>
              </div>
              <div className="flex items-center gap-3 md:gap-6 lg:gap-9">
                <li className="text-white text-sm font-thin">
                  <Link
                    className=" inline-block px-4 py-1 text-white text-sm border-2 border-transparent rounded-md hover:border-blue-500 hover:bg-none hover:text-blue-500 transition duration-1000"
                    href="/"
                  >
                    Home
                  </Link>
                </li>
                <li className="text-white text-sm font-thin">
                  <Link
                    className=" inline-block px-4 py-1 text-white text-sm border-2 border-transparent rounded-md hover:border-blue-500 hover:bg-none hover:text-blue-500 transition duration-1000"
                    href="#project"
                  >
                    Projects
                  </Link>
                </li>
                <li className="text-white text-sm font-thin">
                  <Link
                    className=" inline-block px-4 py-1 text-white text-sm border-2 border-transparent rounded-md hover:border-blue-500 hover:bg-none hover:text-blue-500 transition duration-1000"
                    href="#about"
                  >
                    Aabout
                  </Link>
                </li>
                <li className="text-white text-sm font-thin">
                  <Link
                    className=" inline-block px-4 py-1 text-white text-sm border-2 border-transparent rounded-md hover:border-blue-500 hover:bg-none hover:text-blue-500 transition duration-1000"
                    href="#contact"
                  >
                    Contact
                  </Link>
                </li>
              </div>
            </ul>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
