import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-950">
        <header className="w-full h-[50px] mt-3 mb-12 ">
          <div className="w-full h-full bg-slate-900 max-w-[400px] mx-auto md:max-w-[80%] rounded-lg px-6">
              <ul className=" w-full h-full flex justify-between items-center gap-9">
                  <div className="w-6 h-6"><Link href="/"><img src="dcdc" alt="Logo" /></Link></div>
                  <div className="flex items-center gap-3 md:gap-6 lg:gap-9">
                      <li className="text-white text-sm font-thin "><Link className=" py-1 px-2 rounded-md border-blue-500" href="/">Home</Link></li>
                      <li className="text-white text-sm font-thin "><Link className=" py-1 px-2 rounded-md border-blue-500" href="/projects">Projects</Link></li>
                      <li className="text-white text-sm font-thin "><Link className=" py-1 px-2 rounded-md border-blue-500" href="/about">About</Link></li>
                      <li className="text-white text-sm font-thin "><Link className=" py-1 px-2 rounded-md border-blue-500" href="/contact">Contact</Link></li>
                  </div>
              </ul>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
